apiVersion: v1
kind: Service
metadata:
  name: {{ include "metadata-exporter.fullname" . }}
  namespace: {{ include "metadata-exporter.namespace" . }}
  labels:
    {{- include "metadata-exporter.labels" . | nindent 4 }}
  {{- if or .Values.prometheusAnnotations .Values.service.annotations }}
  annotations:
    {{- if .Values.prometheusAnnotations }}
    prometheus.io/scrape: "true"
    prometheus.io/port: {{ .Values.service.port | quote }}
    prometheus.io/path: /metrics
    {{- end }}
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "metadata-exporter.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
