apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "clickhouse.usersConfigMapName" . }}
  labels:
    {{- include "clickhouse.labels" . | nindent 4 }}
data:
  10-default-user.xml: |
    <clickhouse>
      <users>
        <default>
          {{- if include "clickhouse.auth.secretEnabled" . }}
          <password from_env="{{ include "clickhouse.auth.passwordEnvVar" . }}"/>
          {{- else }}
          <password></password>
          {{- end }}
          {{- if .Values.auth.defaultUser.allowAllNetworks }}
          <networks>
            <ip>::/0</ip>
          </networks>
          {{- else }}
          <networks>
            <ip>::1</ip>
            <ip>127.0.0.1</ip>
          </networks>
          {{- end }}
          <profile>default</profile>
          <quota>default</quota>
          <access_management>1</access_management>
        </default>
      </users>
    </clickhouse>
  20-lightweight-update.xml: |
    <clickhouse>
      <profiles>
        <default>
          {{- if .Values.lightweightUpdate.enabled }}
          {{- if .Values.lightweightUpdate.enableLightweightUpdate }}
          <enable_lightweight_update>1</enable_lightweight_update>
          {{- end }}
          {{- if .Values.lightweightUpdate.allowExperimentalLightweightUpdate }}
          <allow_experimental_lightweight_update>1</allow_experimental_lightweight_update>
          {{- end }}
          {{- if .Values.lightweightUpdate.applyPatchesOnRead }}
          <apply_patches_on_read>1</apply_patches_on_read>
          {{- end }}
          {{- end }}
        </default>
      </profiles>
    </clickhouse>
